### ISSUE TITLE
Demo on GitHub Pages

### ISSUE THREAD

**Issue by jtsimoes** [Mohammad-Farmaan/Dark-Mode-For-Web#2]
Hi!
Awesome tip here!
Can you host this on your GitHub Pages website to make an easy and fast online demo, and provide the link on the description of this repo?
Thanks!

**Comment by Ronnie434** [comment]
Yes. I will do that.

**Comment by zxcodes** [comment]
Yeah sure. You can visit the demo now. I've published it to the GitHub pages. Link in the repo.
